repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
        files: ^backend/.*\.py$
        exclude: ^backend/(\.venv|venv|env)/
        args: [--in-place, --max-line-length=79, --aggressive, --aggressive]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        files: ^backend/.*\.py$
        exclude: ^backend/(\.venv|venv|env)/
        args: [--in-place, --wrap-summaries, "79", --wrap-descriptions, "79"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^backend/.*\.py$
        exclude: ^backend/(\.venv|venv|env)/

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        files: ^backend/.*\.py$
        exclude: ^backend/(\.venv|venv|env)/
        args: [--line-length=79]

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        files: ^backend/.*\.py$
        exclude: ^backend/(\.venv|venv|env)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        files: ^backend/.*\.py$
        exclude: ^backend/(\.venv|venv|env|alembic)/
        additional_dependencies:
          - fastapi==0.115.9
          - pydantic==2.11.5
          - pydantic-settings==2.9.1
          - sqlalchemy==2.0.41
          - alembic==1.16.1
          - types-setuptools
          - types-python-jose
          - types-passlib
          - python-jose[cryptography]
          - passlib[bcrypt]
          - email-validator==2.2.0
          - python-multipart==0.0.20
          - pytest==8.4.0
        args: [--strict, --show-error-codes]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        files: ^backend/.*\.py$
        exclude: ^backend/(\.venv|venv|env)/
        args: ['-s', 'B101']

  - repo: https://github.com/eslint/eslint
    rev: v8.42.0
    hooks:
      - id: eslint
        files: ^frontend/
        types: [javascript, jsx, ts, tsx]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: ^frontend/
